// <auto-generated />
using System;
using ManageBooking.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ManageBooking.Migrations
{
    [DbContext(typeof(BookingContext))]
    [Migration("20230528121312_in")]
    partial class @in
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ManageBooking.Model.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Booking Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<double?>("BillAmount")
                        .HasColumnType("float")
                        .HasColumnName("Bill Amount");

                    b.Property<DateTime>("CheckinDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("Check-in Date");

                    b.Property<DateTime>("CheckoutDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("Check-out Date");

                    b.Property<int>("HotelID")
                        .HasColumnType("int")
                        .HasColumnName("Hotel Id");

                    b.Property<int>("RoomId")
                        .HasColumnType("int")
                        .HasColumnName("Room Id");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("User Id");

                    b.HasKey("Id");

                    b.ToTable("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
