// <auto-generated />
using ManageRooms.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ManageRooms.Migrations
{
    [DbContext(typeof(RoomsContext))]
    [Migration("20230528101329_initializes")]
    partial class initializes
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ManageRooms.Models.Rooms", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Room Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Amenties")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Amenties");

                    b.Property<string>("AvailablityStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Availability Status  Yes or No");

                    b.Property<int>("HotelId")
                        .HasColumnType("int");

                    b.Property<string>("NumberofRoom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Number of rooms");

                    b.Property<double>("RoomPrice")
                        .HasColumnType("float")
                        .HasColumnName("Room Price");

                    b.Property<string>("RoomType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Room Type");

                    b.HasKey("Id");

                    b.ToTable("Rooms");
                });
#pragma warning restore 612, 618
        }
    }
}
