// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RegistrationAndLogin.Context;

#nullable disable

namespace RegistrationAndLogin.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("RegistrationAndLogin.Model.Hotels", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Hotel Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("HotelName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Hotel Name");

                    b.Property<string>("LocationCity")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("City Location");

                    b.Property<string>("LocationCountry")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Country Loacation");

                    b.Property<float?>("Price")
                        .HasColumnType("real")
                        .HasColumnName("Price");

                    b.HasKey("Id");

                    b.ToTable("Hotel");
                });

            modelBuilder.Entity("RegistrationAndLogin.Model.Users", b =>
                {
                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("User Name");

                    b.Property<int?>("Age")
                        .HasColumnType("int")
                        .HasColumnName("Age");

                    b.Property<byte[]>("HashKey")
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("Hash Key");

                    b.Property<byte[]>("Password")
                        .IsRequired()
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("Password");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Role");

                    b.HasKey("UserName");

                    b.ToTable("User");
                });
#pragma warning restore 612, 618
        }
    }
}
